### ISSUE TITLE
How to obtain the environment for the paper

### ISSUE THREAD

**Issue by tianlexm** [xujinming01/TD3AQ#1]
How to obtain the environment for the paper---- ems

**Comment by yanwei-666** [comment]
Hello, can you provide the hppo_noshare file in the agent folder? Thanks

**Comment by xujinming01** [comment]
Thank you for your interest in our work! Due to project confidentiality, we are unable to provide the EMS environment at this time. However, you are welcome to use the algorithms we developed with your own environment, or you can explore the environments available in [Gym](https://github.com/openai/gym) as an alternative.
